"""
🔹 utils.py
---------------------------------
Utility functions for cleaning output and error handling.
"""

def clean_command(raw_command):
    """
    Cleans the output command by removing unwanted characters like backticks.

    Args:
        raw_command (str): The raw command generated by Ollama.

    Returns:
        str: Cleaned `gcloud` command.
    """
    return raw_command.replace("```", "").replace("`", "").strip()
